version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      # Host bind to /home/<login>/data to match the subject rule
      - /home/${LOGIN}/data/mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    depends_on:
      - mariadb
    volumes:
      - /home/${LOGIN}/data/wordpress:/var/www/html
    networks:
      - inception

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - /home/${LOGIN}/data/wordpress:/var/www/html
    networks:
      - inception

  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
    restart: always
    volumes:
      - /home/${LOGIN}/data/redis:/data
    networks:
      - inception

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - "8080:8080"

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
    restart: always
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - /home/${LOGIN}/data/wordpress:/home/ftpuser/wordpress
    secrets:
      - wp_admin_password
    networks:
      - inception

  static:
    container_name: static
    build:
      context: ./requirements/bonus/static
    restart: always
    networks:
      - inception
    ports:
      - "8081:80"

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: always
    networks:
      - inception

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password

